---
title: Data Analysis
---

## Downloading Data

Users can manually download the data from the [S3 bucket](../../index.qmd#available-data).

Data are stored as Parquet datasets in an S3 bucket with the following structure:

```text
s3://phyto-indicator/data/
├── Bottle
│   ├── _metadata
│   ├── ...
│   └── provider_key=Washington_Department_of_Ecology
|       ├── year=XXXX
|       │   └── *.parquet
|       └── ...
├── CTD
│   ├── _metadata
│   ├── ...
│   └── provider_key=Washington_Department_of_Ecology
|       ├── year=XXXX
|       │   └── *.parquet
|       └── ...
├── Mooring
│   ├── _metadata
│   ├── ...
│   └── provider_key=Washington_Department_of_Ecology
|       ├── year=XXXX
|       │   └── *.parquet
|       └── ...
├── Species_Abundance_Biovolume_Community
│   ├── _metadata
│   ├── ...
│   └── provider_key=University_of_Washington
|       ├── year=XXXX
|       │   └── *.parquet
|       └── ...
└── Summary
    ├── _metadata
    └── *.parquet
```

Below are a few options for downloading the data:

1. **[AWS CLI](https://aws.amazon.com/cli/)**: If you have the AWS CLI installed, you can use the following command to download the entire dataset:

   ```bash
   aws s3 cp --recursive s3://phyto-indicator/data/ ./local-data-directory/
   ```

2. **[Cyberduck](https://cyberduck.io/)**: A user-friendly GUI tool that allows you to connect to S3 buckets and download files via drag-and-drop.

3. **[Boto3 (Python)](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html)**: You can use the Boto3 library in Python to programmatically download the data. Check out the [s3.ipynb](./content/analysis/s3.ipynb) notebook for an example of how to do this.

Once the data is downloaded, you can read the Parquet files using libraries such as [Polars](https://pola-rs.github.io/polars-book/user-guide/io/parquet.html) or [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html). A [Python notebook](./content/analysis/python-analysis.ipynb) is provided to assist with reading the downloaded Parquet files.
