---
name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_DATABASE: phyto_indicator
  POSTGRES_USER: actions_runner

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    # Cancel any previous deployments that are still in progress
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create _environment file
        run: |
          echo "POSTGRES_HOST=${{ env.POSTGRES_HOST }}" > _environment
          echo "POSTGRES_PORT=${{ env.POSTGRES_PORT }}" >> _environment
          echo "POSTGRES_DATABASE=${{ env.POSTGRES_DATABASE }}" >> _environment
          echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> _environment
          echo "POSTGRES_PASSWORD=$(cat ~/.actions_runner_pgpassword)" >> _environment
      - name: Test Database Connection
        run: |
          PGPASSWORD=$(cat ~/.actions_runner_pgpassword) psql -U ${{ env.POSTGRES_USER }} -h ${{ env.POSTGRES_HOST }} ${{ env.POSTGRES_DATABASE }} -c "SELECT current_database();"
      # - name: Set up Quarto
      #   uses: quarto-dev/quarto-actions/setup@v2
      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: '4.4.0'
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      # - name: Setup uv
      #   uses: astral-sh/setup-uv@v4
      #   with:
      #     # https://docs.astral.sh/uv/guides/integration/github/#caching
      #     enable-cache: true
      #     cache-dependency-glob: "requirements**.txt"
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: ".python-version"
      - name: Install Python Dependencies
        run: |
          uv venv
          source .venv/bin/activate
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install jupyter
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
