---
name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    # Cancel any previous deployments that are still in progress
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Query Postgres
        run: |
          PGPASSWORD=$(cat ~/.actions_runner_pgpassword) psql -U actions_runner -h localhost phyto_indicator -c "SELECT * FROM d_location limit 5;"
